spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/studyD
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.hbm2ddl.auto: update
  properties:
    hibernate:
      # show_sql: true -> System.out ? ?? ??
      format_sql: true
logging.level:
  org.hibernate.SQL: debug # logger? ?? ??
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
