spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:h2:tcp://localhost/~/studyD
    url : jdbc:mysql://localhost:3306/study_db
    username: root
    password: qwer1234
    #driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
logging.level:
  org.hibernate.SQL: debug

# 세션 타임아웃 설정 - 초 기반
# server.servlet.session.timeout: 1800

# 세션 타임아웃 설정 - 분 기반
server.servlet.session.timeout: 90m